#!/usr/bin/env Rscript
# vim: filetype=r

# Description:
# -----------
# Generate basic statistics from a file whith a single number per line.
# Dependencies: R and the `column` shell command.
#
# Parameters:
# ----------
# stdin: Path to the file which has a single number per line.
#
# Examples:
# --------
# $ spub-stats-generate-summary < data.txt
# N    min  mean      median  percentile_95  percentile_99  max
# 503  47   384.6839  450     675.9          746.82         1032

# Build a numeric vector.
x <- as.numeric(readLines("stdin"))

# Custom basic statistics.
basic_stats <- data.frame(
    N = length(x), min = min(x), mean = mean(x), median = median(x),
    percentile_95 = quantile(x, c(.95)), percentile_99 = quantile(x, c(.99)),
    max = max(x))

# Print output. Tabular formatting is done by the `column` command.
temp_file <- tempfile("basic_stats_", fileext = ".csv")
write.csv(round(basic_stats, 4), file = temp_file, row.names = FALSE, quote = FALSE)
system(paste("column -s, -t", temp_file))
. <- file.remove(temp_file)
