#!/bin/bash

# Description:
# -----------
# Get a OS label for the current machine.
#
# Parameters: (none).
# ----------

UNAME_OUTPUT="$(uname -s)"

case "${UNAME_OUTPUT}" in
  Linux*)   OS=linux;;
  Darwin*)  OS=mac;;
  CYGWIN*)  OS=cygwin;;
  MINGW*)   OS=mingw;;
  *)        OS="unknown:${UNAME_OUTPUT}"
esac

echo ${OS}

