#!/bin/bash

# Description:
# -----------
# From a Git repository in the current directory and provided a merge commit,
# get the range of commits of the merged topic branch. It is not required that
# HEAD is at any specific position.
#
# Parameters:
# ----------
# $1: Reference to the merge commit.
#
# Examples:
# --------
# Get the merged commits of the merge commit `8ef259931b8`. This would get the
# commits that a tool like GitHub or BitBucket would report as the "commits of
# the PR".
# ```
# $ g-topic-range 8ef259931b8
# 679f3915cc0^2 ^8f50637952caf65bf6cf73c2d959c38bbb677719
# ```
# The output of the script is meant to be used by a Git command, e.g.:
# git log --oneline $(g-topic-range 8ef259931b8)

merge_base_commit=$(git merge-base $1^ $1^2)
echo $1^2 ^$merge_base_commit
