#!/bin/zsh -f

typeset -r DATA_FILE='/usr/local/share/kitty/zen_mode.zsh'

source "${DATA_FILE}"
zen_mode_tab_key="$(spub-term-kitty-zen-mode-tab-key)"
zen_mode_enabled="${zen_mode[${zen_mode_tab_key}]}"

# Get list of window ids in the focused tab.
window_ids=$(kitty @ ls --match-tab=state:focused | jq '.[0].tabs[0].windows[].id')

# Set the padding for every window.
while IFS='\n' read -r window_id; do
  if [[ "${zen_mode_enabled}" = 'true' ]]; then
    kitty @ set-spacing --match=id:${window_id} \
      padding-left=4 padding-right=4 padding-top=0 padding-bottom=0
    continue
  fi
  kitty @ set-spacing --match=id:${window_id} \
    padding-left=405 padding-right=405 padding-top=0 padding-bottom=0
done <<< $(echo "${window_ids}")

# Toggle Zen mode.
if [[ "${zen_mode_enabled}" = 'true' ]]; then
  zen_mode[${zen_mode_tab_key}]='false'
  typeset -p zen_mode > "${DATA_FILE}"
else
  zen_mode[${zen_mode_tab_key}]='true'
  typeset -p zen_mode > "${DATA_FILE}"
fi
