#!/bin/bash

UNAME_OUTPUT="$(uname -s)"

case "${UNAME_OUTPUT}" in
  Linux*)   OS=linux;;
  Darwin*)  OS=mac;;
  CYGWIN*)  OS=cygwin;;
  MINGW*)   OS=mingw;;
  *)        OS="unknown:${UNAME_OUTPUT}"
esac

echo ${OS}

