#!/bin/bash
source "$SPUB/config/delta-default-opts.sh"

# Description:
# -----------
# Conditionally load search pattern on Delta's pager if a match can be found.
# This has the purpose of always properly setting the navigation pattern for
# diffs, when available.
#
# This script is meant to be used as a pager for Git sub-commands, e.g.:
# ```
#[pager]
#  log = spub-git-delta-navigate
#  diff = spub-git-delta-navigate
#  show = spub-git-delta-navigate
#  reflog = spub-git-delta-navigate
# ```
#
# The Delta repository: <https://github.com/dandavison/delta>.
#
# Parameters: (none).
# ----------

# Amount of lines to read from stdin used to determine if
# loading a pattern into the pager is needed. This should
# be set to the amount of lines of a single screen.
SAMPLE_SIZE=$(tput lines)
# Array storing the joined sample lines.
SAMPLE_LINES=()
# Pattern used to determine if loading a pattern into the
# pager would be useful.
GIT_DIFF_PATTERN='diff --git a/.* b/.*'

# Pager configuration.
PAGER_WITHOUT_PATTERN='less -iRXFM'
PAGER_WITH_PATTERN="less -iRXFM --pattern \
  'commit [a-z0-9]{40}|Δ|•|added: |removed: '"

# Enable debug logging.
DEBUG_ENABLED=0
DEBUG_LOG=''

function echo_sample_and_remaining_stdin {
  test $DEBUG_ENABLED -eq 1 && echo "$DEBUG_LOG"
  for i in ${!SAMPLE_LINES[@]}; do
    echo "${SAMPLE_LINES[$i]}"
  done
  while IFS='$\n' read -r line; do
    echo "$line"
  done
}

function execute_pipeline {
  local sample_lines_concatenated=''
  local current_line_number=1
  local eof_reached=1

  # Join sample lines.
  while IFS='$\n' read -r line; do
    SAMPLE_LINES+=("$line")
    sample_lines_concatenated="$sample_lines_concatenated$line\n"
    if [[ $current_line_number -eq $SAMPLE_SIZE ]]; then
      eof_reached=0
      break
    fi
    current_line_number=$(( $current_line_number + 1 ))
  done

  # Determine if stdin is navigable based on the sample.
  local stdin_is_navigable=$(echo -e "$sample_lines_concatenated" \
    | grep -E "$GIT_DIFF_PATTERN")

  # Decide if less should have a search pattern loaded.
  if [[ -n "$stdin_is_navigable" && $eof_reached -eq 0 ]]; then
    DEBUG_LOG='YES - stdin is navigable and would benefit from it.'
    local pager="$PAGER_WITH_PATTERN"
  else
    DEBUG_LOG='NO - stdin is not navigable or would not benefit from it.'
    local pager="$PAGER_WITHOUT_PATTERN"
  fi

  # Execute pipeline.
  echo_sample_and_remaining_stdin \
    | delta "${DELTA_DEFAULT_OPTS[@]}" --pager="$pager"
}

execute_pipeline

