#!/bin/bash

# Description:
# -----------
# Clean the provided list of files. Notice that "cleaning" means to remove the
# file's contents, but don't delete the file.
#
# Parameters:
# ----------
# $@: List of files to clean.
#
# Examples:
# --------
# Clean files `file{1..3}.txt`.
# ```
# $ spub-os-clean-files file1.txt file2.txt file3.txt
# Cleaned contents of: file1.txt
# Cleaned contents of: file2.txt
# Cleaned contents of: file3.txt
# ```
# The previous notation also works:
# ```
# $ spub-os-clean-files file{1..3}.txt
# Cleaned contents of: file1.txt
# Cleaned contents of: file2.txt
# Cleaned contents of: file3.txt
# ```

for file in "$@"; do
  :> "$file" && echo "Cleaned contents of: $file"
done

