#!/bin/zsh -f

# ~ Parameters
# $1: Split direction, either 'v' (vertical) or 'h' (horizontal).

case "${1}" in
  h)
    kitty @ launch --location=hsplit --cwd=current
    ;;
  v)
    kitty @ launch --location=vsplit --cwd=current
    ;;
esac

# ZEN MODE SUPPORT

source '/usr/local/share/kitty/zen_mode.zsh'
zen_mode_tab_key="$(spub-term-kitty-zen-mode-tab-key)"
zen_mode_enabled="${zen_mode[${zen_mode_tab_key}]}"

# Change window padding.
if [[ "${zen_mode_enabled}" = 'true' ]]; then
  kitty @ set-spacing --match=state:focused \
    padding-left=250 padding-right=250 padding-top=0 padding-bottom=0
fi
